package io.nexus.plugin

import io.nexus.libbox.Libbox
import org.json.JSONArray
import org.json.JSONObject
import java.net.InetAddress

/**
 * Enforces the ADR-0001 power decisions that live in config rather than in code.
 *
 * Why this exists: the TUN stack and the health-check intervals are the two biggest battery
 * levers we have, and both are *config fields*. That means a template edit, a bad subscription
 * import, or a well-meaning UI change can silently undo the product. A decision that important
 * should not be enforceable only by convention.
 *
 * Runs once per connect, on the config string, before the core sees it. Not a hot path.
 *
 * ARCHITECTURAL NOTE: the authoritative home for this is Go, not Kotlin — ADR-0002 §2 puts
 * config generation on the native/Go side precisely so there is one implementation rather than
 * one per platform. This Kotlin version is a stopgap so the Android client is correct today;
 * when `nexuscore` grows config generation, this class should shrink to an assertion that
 * logs and reports, and the rewriting should move across. Until then, the Apple client needs
 * an equivalent — track that as a real task, not a TODO comment.
 */
internal object ConfigGuard {

    private const val TAG = "NexusConfigGuard"

    /** ADR-0001 §5.4 preference. No longer a hard requirement - see enforceTunStack. */
    private const val PREFERRED_STACK = "system"

    /**
     * Floor for any url-test / health-check interval, in seconds.
     *
     * ADR-0001 §2.1: a 100-node group at the Clash-lineage 300s default is 100 TLS handshakes
     * every five minutes, screen off, forever. We do not ship that. 600s is already generous;
     * the real mitigation is that the Go coalescer suspends these entirely when the screen is
     * off, and this floor only bounds the damage while the screen is on.
     */
    private const val MIN_HEALTH_CHECK_SECONDS = 600

    /** Tag of the DNS server holding the natively-resolved outbound addresses. */
    private const val HOSTS_DNS_TAG = "dns-hosts"

    class RejectedException(message: String) : IllegalArgumentException(message)

    /**
     * Returns the config to hand to the core: rejected if it violates a hard decision,
     * rewritten if it merely exceeds a policy bound.
     */
    fun enforce(config: String): String {
        val root = try {
            JSONObject(config)
        } catch (e: Exception) {
            throw RejectedException("config is not valid JSON: ${e.message}")
        }

        enforceTunStack(root)
        val clamped = clampHealthChecks(root)

        // WHY THE SYSTEM RESOLVER, AND WHY THAT IS NOT A CONTRADICTION.
        //
        // Everything else in this app treats the local resolver as hostile, and it is. But the
        // proxy server's own hostname is the one lookup that must happen BEFORE the tunnel
        // exists, and on this network the encrypted alternatives are not reachable:
        //
        //   dns: lookup failed for <server>:
        //     read tcp ...->1.1.1.1:443: read: connection reset by peer
        //
        // DoH to Cloudflare is reset by the ISP. Pointing default_domain_resolver at it made
        // EVERY connection fail, because every connection needs the server's address first.
        //
        // So: the system resolver, with a guard. It is the only resolver that answers here, and
        // it answers correctly for these domains in practice - a paid VPN panel's hostname is
        // not on the national blocklist. What it must never do is hand back a filtering
        // blackhole unnoticed, so assertUsableAddress rejects the shapes a poisoned answer
        // takes. A loud failure beats a tunnel pointed at 10.10.34.35.
        val resolved = resolveOutboundServers(root)

        if (clamped > 0) {
            NexusLog.w(TAG, "clamped $clamped health-check interval(s) to ${MIN_HEALTH_CHECK_SECONDS}s")
        }

        if (resolved > 0) {
            NexusLog.i(TAG, "pre-resolved $resolved outbound server hostname(s)")
        }


        // Say out loud what we were actually handed. A config generated by an older build and
        // replayed from storage looks identical from the outside to a freshly generated one,
        // and that ambiguity cost a full debug cycle: the DNS block was added, the APK was
        // rebuilt, and the device kept using a stored config that predated it.
        val dns = root.optJSONObject("dns")
        NexusLog.i(
            TAG,
            "config accepted: dns=" +
                if (dns == null) "ABSENT (DNS will fall back to the system resolver)"
                else "present(servers=${dns.optJSONArray("servers")?.length() ?: 0}, " +
                    "final=${dns.optString("final", "-")})",
        )

        logProxyOutbound(root)

        val result = root.toString()

        // Hand it to sing-box's OWN parser before the core tries to run it.
        //
        // Everything above checks Nexus policy; this checks that the document is a valid
        // sing-box config at all. Without it, a schema mistake surfaces as whatever the core
        // does at runtime with a half-understood document — which in practice has meant a
        // tunnel that establishes and carries nothing, with the real cause buried.
        //
        // sing-box's config schema moves between releases (the DNS server syntax changed in
        // 1.12, sniff became a route action in 1.11), and we generate config in TypeScript for
        // now, so a generator that drifts from the pinned core is a live risk rather than a
        // theoretical one. This turns that into one clear error at connect time.
        try {
            Libbox.checkConfig(result)
        } catch (e: Exception) {
            throw RejectedException("sing-box rejected the config: ${e.message}")
        }

        return result
    }

    /**
     * Reject, do not rewrite.
     *
     * A config asking for the gvisor stack is not a config with a bad number in it — it is a
     * config written against a different set of assumptions, and silently flipping the field
     * would produce a tunnel whose behaviour does not match what its author expected. Fail
     * loudly and let a human look.
     */
    private fun enforceTunStack(root: JSONObject) {
        val inbounds = root.optJSONArray("inbounds") ?: return
        for (i in 0 until inbounds.length()) {
            val inbound = inbounds.optJSONObject(i) ?: continue
            if (inbound.optString("type") != "tun") continue

            // WARN, DO NOT REJECT.
            //
            // This used to throw for any stack other than "system", enforcing ADR-0001 §5.4 as
            // an absolute. On device that rule turned out to be enforcing a stack which carried
            // UDP and dropped TCP entirely - so the guard was protecting a battery policy on a
            // tunnel that moved no traffic.
            //
            // A policy guard should make the expensive choice visible, not make a working
            // configuration impossible. The preference is still recorded, loudly, on every
            // connect that departs from it.
            val stack = inbound.optString("stack", "")
            if (stack.isEmpty()) {
                // Absent means the core's default. Pin it so the log always names what ran.
                inbound.put("stack", PREFERRED_STACK)
            } else if (stack != PREFERRED_STACK) {
                NexusLog.w(
                    TAG,
                    "tun stack is \"$stack\", not \"$PREFERRED_STACK\" (ADR-0001 §5.4). " +
                        "gvisor reassembles TCP in userspace and costs CPU per packet, which is " +
                        "battery. Measure it in bench/B-04 before this becomes permanent."
                )
            }

            // ADR-0001 §5.4: process_name / find_process routing is a documented CPU sink
            // (SagerNet/sing-box#3934) because it forces an owner lookup per connection.
            if (inbound.optBoolean("auto_redirect", false)) {
                NexusLog.w(TAG, "auto_redirect enabled — verify against bench/B-04 before shipping")
            }
        }
    }

    /**
     * Replace outbound server HOSTNAMES with IP literals, resolved by Android.
     *
     * ================= WHY DNS IS TAKEN OFF THE CRITICAL PATH =================
     *
     * The core cannot resolve its own server address until the tunnel is up, and the tunnel
     * cannot come up until it resolves its own server address. That circularity is normally
     * broken by a "direct" resolver that queries outside the tunnel - but on a censored network
     * every such path is attacked:
     *
     *   plain UDP/53  -> answered by the filter (observed: 10.10.34.35, an RFC1918 blackhole)
     *   DoH 1.1.1.1   -> TCP reset (observed: "read tcp ...->1.1.1.1:443: connection reset")
     *
     * With both blocked, the server hostname never resolves and every outbound fails:
     *
     *   connection: listen packet connection using outbound/vless[proxy]:
     *     lookup proxy.example.net: connection reset by peer
     *
     * Android's own resolver, however, demonstrably works on this device - the subscription was
     * downloaded through it moments earlier. So we resolve here, natively, once, and hand the
     * core an address it never has to look up.
     *
     * TLS IS PRESERVED. `server` becomes an IP; `tls.server_name` keeps the hostname, which is
     * what SNI and REALITY actually authenticate against. Substituting the IP without fixing
     * server_name would send the wrong SNI and fail the handshake - so when tls is enabled and
     * server_name is missing, we set it to the original hostname.
     *
     * This is a workaround for a hostile network, not the end state. The principled fix is to
     * implement localDNSTransport() so the core can use the platform resolver itself.
     *
     * =========================================================================
     */
    private fun resolveOutboundServers(root: JSONObject): Int {
        val outbounds: JSONArray = root.optJSONArray("outbounds") ?: return 0

        // host -> every usable address for it. Shared across outbounds, so several nodes on
        // one panel hostname cost one lookup and produce one entry.
        val resolved = LinkedHashMap<String, List<InetAddress>>()

        for (i in 0 until outbounds.length()) {
            val outbound = outbounds.optJSONObject(i) ?: continue
            val host = outbound.optString("server", "")
            if (host.isEmpty() || isIpLiteral(host)) continue

            // Resolve once per hostname. Reaching the far side of this block means the
            // host has usable addresses recorded - every failure path inside continues.
            if (!resolved.containsKey(host)) {
                // getAllByName, not getByName.
                //
                // getByName returns one address and discards the rest, which pinned every
                // connection to a single A record. If that one was dead or wrong there was no
                // second attempt, because the core never saw the alternatives. Keeping them
                // all is what lets sing-box retry.
                val found = runCatching { InetAddress.getAllByName(host).toList() }
                    .getOrElse { emptyList() }

                if (found.isEmpty()) {
                    // Leave the hostname alone. The core may still manage it through
                    // default_domain_resolver, and failing the whole connect because one
                    // lookup missed would be worse than letting it try.
                    NexusLog.w(TAG, "could not resolve $host; leaving the hostname for the core")
                    continue
                }

                // Drop poisoned answers and keep the rest. Refusing the config outright is
                // reserved for the case where NOTHING survives: one bad address among several
                // is a filter doing half a job, not a reason to refuse to connect.
                val usable = found.filter { unusableReason(it) == null }
                if (usable.isEmpty()) {
                    // Everything came back poisoned. Re-check the first one purely to raise
                    // the existing, carefully worded rejection with the right reason in it.
                    assertUsableAddress(host, found.first())
                    continue
                }

                resolved[host] = usable

                // i(), not d(). This was debug-only, and v1.1.0's release gating compiled it
                // out of exactly the builds users run - which is why a wrong resolution could
                // not be diagnosed from a bug report. It is the single most useful line when a
                // node connects to the wrong place, and a hostname plus an address the user
                // already has is a far smaller disclosure than the outbound itself (still
                // debug-only, see logProxyOutbound).
                NexusLog.i(TAG, "resolved $host -> ${usable.joinToString { it.hostAddress ?: "?" }}")
            }

            // Back-fill SNI when the link carried none. Still needed even though `server` now
            // keeps the hostname: an outbound with TLS enabled and no server_name lets the
            // core derive one, and for REALITY that is not necessarily the same string.
            val tls = outbound.optJSONObject("tls")
            if (tls != null && tls.optBoolean("enabled", false) &&
                tls.optString("server_name", "").isEmpty()
            ) {
                tls.put("server_name", host)
            }

            // THE ADDRESS IS SUPPLIED; THE HOSTNAME IS KEPT.
            //
            // `server` used to be overwritten with an IP literal. That worked on networks
            // where DNS is blocked and broke REALITY, because the outbound then had no
            // hostname of its own and the connection was pinned to one address that might not
            // be the right server. Removing the rewrite fixed REALITY and broke the blocked
            // case instead - the device could not resolve at all:
            //
            //     dns: lookup failed for <server>: read tcp ...->1.1.1.1:443: connection reset
            //
            // Pointing the outbound at a `hosts` transport gets both. The core is handed the
            // answer, so nothing is looked up at connect time and no resolver has to be
            // reachable; and `server` stays a hostname, so SNI, REALITY and retry-across-
            // addresses all behave normally.
            //
            // It has to be per-outbound rather than a dns rule. route.default_domain_resolver
            // pins outbound resolution to one transport and skips dns.rules entirely -
            // dns/router.go:1277 takes `if options.Transport != nil` straight to client.Lookup
            // - so a rule matching this hostname would never be consulted.
            outbound.put(
                "domain_resolver",
                JSONObject()
                    .put("server", HOSTS_DNS_TAG)
                    .put("strategy", "prefer_ipv4"),
            )
        }

        if (resolved.isNotEmpty()) injectHostsServer(root, resolved)
        return resolved.size
    }

    /**
     * Publish the resolved addresses as a `hosts` DNS server.
     *
     * sing-box's hosts transport takes a predefined map of name to addresses
     * (option/dns.go:179) - a baked-in answer, with no query, no transport and no network
     * behind it. That is what makes a connect possible on a network where every resolver the
     * device can reach is blocked or lying.
     *
     * If the config carries no dns block, do nothing. Synthesising one here would paper over a
     * config with larger problems, and every config this app generates has one.
     */
    private fun injectHostsServer(root: JSONObject, resolved: Map<String, List<InetAddress>>) {
        val dns = root.optJSONObject("dns")
        if (dns == null) {
            NexusLog.w(TAG, "config has no dns block; skipping the hosts injection")
            return
        }

        val predefined = JSONObject()
        for ((host, addresses) in resolved) {
            val list = JSONArray()
            for (address in addresses) list.put(address.hostAddress)
            predefined.put(host, list)
        }

        val hostsServer = JSONObject()
            .put("type", "hosts")
            .put("tag", HOSTS_DNS_TAG)
            .put("predefined", predefined)

        // Prepended rather than appended. Servers are selected by tag, not by order, so this
        // is presentation only - it puts the baked-in answers at the top of the block someone
        // reading a dumped config looks at first.
        val existing = root.optJSONObject("dns")?.optJSONArray("servers")
        val servers = JSONArray().put(hostsServer)
        if (existing != null) {
            for (i in 0 until existing.length()) servers.put(existing.get(i))
        }
        dns.put("servers", servers)
    }

    private fun isIpLiteral(host: String): Boolean =
        host.matches(Regex("^[0-9.]+$")) || host.contains(":")

    /** Returns the number of intervals clamped. */
    private fun clampHealthChecks(root: JSONObject): Int {
        var clamped = 0
        val outbounds = root.optJSONArray("outbounds") ?: return 0

        for (i in 0 until outbounds.length()) {
            val outbound = outbounds.optJSONObject(i) ?: continue
            if (outbound.optString("type") !in setOf("urltest", "selector")) continue

            val interval = outbound.optString("interval", "")
            val seconds = parseDuration(interval)
            if (seconds != null && seconds < MIN_HEALTH_CHECK_SECONDS) {
                outbound.put("interval", "${MIN_HEALTH_CHECK_SECONDS}s")
                clamped++
            } else if (interval.isEmpty()) {
                // No interval means the core's default, which is short. Pin it.
                outbound.put("interval", "${MIN_HEALTH_CHECK_SECONDS}s")
                clamped++
            }
        }
        return clamped
    }

    /** Parses the Go duration subset sing-box actually emits: "300s", "5m", "1h". */
    private fun parseDuration(value: String): Int? {
        if (value.isEmpty()) return null
        val number = value.dropLast(1).toIntOrNull() ?: return null
        return when (value.last()) {
            's' -> number
            'm' -> number * 60
            'h' -> number * 3600
            else -> null
        }
    }
    /**
     * Print the proxy outbound we are about to run, with the secrets stripped.
     *
     * WHY THIS IS WORTH THE LOG LINE
     *
     * The tunnel plumbing and the outbound are two different failure domains, and from the
     * outside they look identical: nothing loads. Distinguishing them cost several debug
     * cycles. The case that forced this was
     *
     *   connection: connection download closed: unknown version: 72
     *
     * from the VLESS client. 72 is 0x48, ASCII 'H' - the server's first response byte was the
     * start of "HTTP/1.1", so whatever answered was not speaking VLESS. That is either a dead
     * or wrong endpoint, or a transport the URI asked for and our parser dropped (v2ray's
     * `headerType=http` TCP obfuscation produces exactly this symptom, because the real server
     * prefixes a fake HTTP response that an un-obfuscated client reads as a version byte).
     *
     * Those two causes need completely different fixes, and only the generated outbound tells
     * them apart. Without this line the only way to find out is to ask the user to paste a
     * subscription link into a chat window, which is both slow and a credential leak.
     *
     * REDACTION IS NOT OPTIONAL: uuid/password/private keys are the whole credential. Logcat
     * is readable by anything holding READ_LOGS and gets pasted into bug reports verbatim.
     * Public keys and SNI stay - they are transmitted in the clear on the wire anyway, and
     * they are exactly the fields that are usually wrong.
     */
    private fun logProxyOutbound(root: JSONObject) {
        val outbounds = root.optJSONArray("outbounds") ?: return
        for (i in 0 until outbounds.length()) {
            val outbound = outbounds.optJSONObject(i) ?: continue
            if (outbound.optString("tag") != "proxy") continue
            runCatching {
                NexusLog.d(TAG) { "proxy outbound: ${redact(JSONObject(outbound.toString()))}" }
            }.onFailure { NexusLog.w(TAG, "could not describe the proxy outbound: ${it.message}") }
            return
        }
        NexusLog.w(TAG, "no outbound tagged \"proxy\" - the route final has nothing to point at")
    }

    /** Recursively replace credential-bearing values with a placeholder, in place. */
    private fun redact(node: JSONObject): JSONObject {
        for (key in node.keys().asSequence().toList()) {
            when {
                key in SECRET_KEYS -> node.put(key, "***")
                else -> (node.opt(key) as? JSONObject)?.let { redact(it) }
            }
        }
        return node
    }

    private val SECRET_KEYS = setOf(
        "uuid", "password", "private_key", "psk", "auth", "auth_str", "token",
    )

    /**
     * Refuse an answer that cannot be a real proxy server.
     *
     * This is the guard that makes using the system resolver defensible. A censor's answer is
     * not subtle - it points somewhere that could never host the service:
     *
     *   inbound/tun[tun-in]: inbound packet connection to 10.10.34.35:443
     *
     * That address is RFC1918 - private, and therefore unreachable across the internet, so no
     * public proxy server can be behind it. Redirecting blocked lookups to a private-range
     * blackhole is a common filtering technique; the particular address varies by network, so
     * this checks the PROPERTY rather than matching a list of known ones.
     *
     * Without this check the tunnel connects to the blackhole, every flow closes after ~200ms
     * having moved nothing, and the app reports "connected" the whole time. That is the worst
     * possible failure: silent, and it looks like the server's fault.
     *
     * Rejecting instead means the user gets a sentence naming the problem.
     */
    /**
     * Why this address cannot be a real proxy server, or null if it can.
     *
     * Split out of assertUsableAddress because there are now two callers wanting different
     * things from the same judgement: the resolver filters a list and carries on, while the
     * rejection path below still wants the fully worded exception. One definition of
     * "poisoned", two uses - rather than two definitions that drift.
     */
    private fun unusableReason(address: InetAddress): String? = when {
        address.isLoopbackAddress -> "loopback"
        address.isAnyLocalAddress -> "wildcard"
        address.isLinkLocalAddress -> "link-local"
        address.isMulticastAddress -> "multicast"
        // A proxy server on a private address is not reachable from this device over the
        // internet; the only way to get one back is interception.
        address.isSiteLocalAddress -> "private (RFC1918)"
        else -> null
    }

    private fun assertUsableAddress(host: String, address: InetAddress) {
        val reason = unusableReason(address) ?: return

        throw RejectedException(
            "DNS returned a $reason address for $host (${address.hostAddress}). " +
                "That is not a reachable server - the local resolver is almost certainly " +
                "being intercepted. Try another node, or a different network."
        )
    }

}
